// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3UKPUHMNOX-zJ5dlZ3f-4WQBX4quJi_E',
    appId: '1:882250366819:web:72530da8086057d37f9d56',
    messagingSenderId: '882250366819',
    projectId: 'actividad-query',
    authDomain: 'actividad-query.firebaseapp.com',
    storageBucket: 'actividad-query.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmI0zEYzLoUyDT6KA2eArDVLwpSK3YqRE',
    appId: '1:882250366819:android:a96b5a2056baa3717f9d56',
    messagingSenderId: '882250366819',
    projectId: 'actividad-query',
    storageBucket: 'actividad-query.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpnriVZTvnrOYlpuamwhZzXIDwXD0KmFA',
    appId: '1:882250366819:ios:762858a3190a3f2f7f9d56',
    messagingSenderId: '882250366819',
    projectId: 'actividad-query',
    storageBucket: 'actividad-query.appspot.com',
    iosBundleId: 'com.example.query',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpnriVZTvnrOYlpuamwhZzXIDwXD0KmFA',
    appId: '1:882250366819:ios:266b9899dc2ac0577f9d56',
    messagingSenderId: '882250366819',
    projectId: 'actividad-query',
    storageBucket: 'actividad-query.appspot.com',
    iosBundleId: 'com.example.query.RunnerTests',
  );
}
